Create register partner of airplane's brand
cg-traveloka/cg-traveloka-service pull request #5
Opened 2024-03-08 15:58 UTC by vietvu1996

Review my code, just only airplane's brand. About airport's location, I haven't done it yet.

2024-03-08 16:50 UTC, dinhhieu240901 requested changes

2024-03-08 16:50 UTC, dinhhieu240901 commented on src/main/java/com/cgtravelokaservice/service/implement/AirplaneBrandService.java
> +            AirPlantBrand brand = new AirPlantBrand();
Use the object's transport instead of using the new object

2024-03-09 04:30 UTC, LamChiHung reviewed
the method setLogoUrl(AirPlantBrand airPlantBrand, MultipartFile logoUrl) of AirplaneBrandService is not correct. Please view the comment attached in the method

2024-03-09 04:33 UTC, LamChiHung commented on src/main/java/com/cgtravelokaservice/service/implement/AirplaneBrandService.java
> +            AirPlantBrand brand = new AirPlantBrand();
why you create a new AirPlantBrand (brand) object? you need to set the image url to the parameter AirPlantBrand(airPlantBrand)

2024-03-09 04:41 UTC, LamChiHung reviewed
You need to fix this problem to solve the exception

2024-03-09 04:41 UTC, LamChiHung commented on src/main/java/com/cgtravelokaservice/controller/AirplaneBrandController.java
> +        airplaneBrandService.setLogoUrl(airPlantBrand, logoUrl);
this airPlantBrand object will be not working, because it is not the entity in database yet. You need to assign: airPlantBrand  = airplaneBrandRepo.saveAndFlush(airPlantBrand); this time the airPlantBrand is a entity in database because the save method is return a entity in database

2024-03-09 09:33 UTC, vietvu1996 commented on src/main/java/com/cgtravelokaservice/controller/AirplaneBrandController.java
> +        return ResponseEntity.ok().body(airPlantBrand);
Thank you

2024-03-09 09:33 UTC, vietvu1996 commented on src/main/java/com/cgtravelokaservice/service/implement/AirplaneBrandService.java
> +            AirPlantBrand brand = new AirPlantBrand();
Understood

2024-03-09 12:37 UTC, vietvu1996 commented on src/main/java/com/cgtravelokaservice/controller/AirplaneBrandController.java
> +        airplaneBrandService.setLogoUrl(airPlantBrand, logoUrl);
Got it

2024-03-10 11:10 UTC, dinhhieu240901 approved these changes
Good

2024-03-10 13:18 UTC, thaonguyen011 approved these changes
good

2024-03-10 13:18 UTC, thaonguyen011 approved these changes
good

2024-03-10 13:55 UTC, LamChiHung approved these changes
well done

2024-03-10 13:56 UTC, merged